import { FA_HOW_TO_USE, translateIngredientsFa } from './product-fa'

const PRODUCTS_SOURCE = [
  // Skincare
  { id: 1, name: 'Hydrating Face Serum', price: 45, category: 'skincare', image: '/hydrating-face-serum.jpg', images: ['/hydrating-face-serum.jpg', '/hydrating-face-serum.jpg', '/hydrating-face-serum.jpg'], ingredients: ['Hyaluronic Acid', 'Vitamin E', 'Aloe Vera Extract', 'Green Tea Extract'], howToUse: 'Apply 2-3 drops to clean skin. Gently massage until absorbed. Use morning and evening.' },
  { id: 2, name: 'Eye Cream', price: 52, category: 'skincare', image: '/eye-cream-luxury.jpg', images: ['/eye-cream-luxury.jpg', '/eye-cream-luxury.jpg', '/eye-cream-luxury.jpg'], ingredients: ['Retinol', 'Peptides', 'Caffeine', 'Hyaluronic Acid'], howToUse: 'Dab small amount around eyes. Pat gently with ring finger. Use morning and night.' },
  { id: 3, name: 'Moisturizer SPF', price: 62, category: 'skincare', image: '/moisturizer-spf-sunscreen.jpg', images: ['/moisturizer-spf-sunscreen.jpg', '/moisturizer-spf-sunscreen.jpg', '/moisturizer-spf-sunscreen.jpg'], ingredients: ['SPF 30', 'Jojoba Oil', 'Niacinamide', 'Ceramides'], howToUse: 'Apply generously to face and neck. Wait 15 minutes before sun exposure. Reapply every 2 hours.' },
  { id: 4, name: 'Facial Cleanser', price: 38, category: 'skincare', image: '/facial-cleanser-luxury.jpg', images: ['/facial-cleanser-luxury.jpg', '/facial-cleanser-luxury.jpg', '/facial-cleanser-luxury.jpg'], ingredients: ['Chamomile Extract', 'Glycerin', 'Sodium Cocoyl Isethionate', 'Vitamin B5'], howToUse: 'Wet face with lukewarm water. Massage cleanser for 30 seconds. Rinse thoroughly with water.' },
  { id: 5, name: 'Night Cream', price: 58, category: 'skincare', image: '/night-cream-moisturizer.jpg', images: ['/night-cream-moisturizer.jpg', '/night-cream-moisturizer.jpg', '/night-cream-moisturizer.jpg'], ingredients: ['Shea Butter', 'Retinol', 'Squalane', 'Peptides'], howToUse: 'Apply to face and neck before bed. Use 3-4 nights per week for best results.' },
  { id: 6, name: 'Face Mask', price: 42, category: 'skincare', image: '/luxury-face-mask-skincare.jpg', images: ['/luxury-face-mask-skincare.jpg', '/luxury-face-mask-skincare.jpg', '/luxury-face-mask-skincare.jpg'], ingredients: ['Kaolin Clay', 'Green Tea', 'Charcoal', 'Lavender Oil'], howToUse: 'Apply evenly to face. Leave for 10-15 minutes. Rinse with warm water. Use 2x weekly.' },
  { id: 7, name: 'Toner', price: 35, category: 'skincare', image: '/face-toner-skincare.jpg', images: ['/face-toner-skincare.jpg', '/face-toner-skincare.jpg', '/face-toner-skincare.jpg'], ingredients: ['Rose Water', 'Witch Hazel', 'Glycerin', 'Niacinamide'], howToUse: 'Apply with cotton pad after cleansing. Gently swipe over face and neck. Follow with moisturizer.' },
  { id: 8, name: 'Retinol Treatment', price: 68, category: 'skincare', image: '/retinol-treatment-skincare.jpg', images: ['/retinol-treatment-skincare.jpg', '/retinol-treatment-skincare.jpg', '/retinol-treatment-skincare.jpg'], ingredients: ['Retinol', 'Peptides', 'Squalane', 'Vitamin E'], howToUse: 'Use 2-3x weekly at night. Start with pea-sized amount. Gradually increase frequency. Use SPF during day.' },
  { id: 9, name: 'Silk Serum', price: 49.99, category: 'skincare', image: '/luxury-purple-cosmetic-serum-bottle.jpg', images: ['/luxury-purple-cosmetic-serum-bottle.jpg', '/luxury-cosmetic-bottle-detail.jpg', '/luxury-cosmetic-packaging.jpg'], ingredients: ['Silk Protein', 'Hyaluronic Acid', 'Rose Hip Oil', 'Vitamin C'], howToUse: 'Apply 3-4 drops to clean skin. Massage gently until absorbed. Use day and night.' },
  { id: 10, name: 'Lavender Mask', price: 39.99, category: 'skincare', image: '/luxury-purple-face-mask-jar.jpg', images: ['/luxury-purple-face-mask-jar.jpg', '/luxury-purple-face-mask-jar.jpg', '/luxury-purple-face-mask-jar.jpg'], ingredients: ['Lavender Extract', 'Aloe Vera', 'Chamomile', 'Glycerin'], howToUse: 'Apply mask evenly. Relax for 15-20 minutes. Rinse with lukewarm water. Use 2-3x weekly.' },
  { id: 11, name: 'Pearl Cream', price: 59.99, category: 'skincare', image: '/luxury-white-pearl-cream-jar.jpg', images: ['/luxury-white-pearl-cream-jar.jpg', '/luxury-white-pearl-cream-jar.jpg', '/luxury-white-pearl-cream-jar.jpg'], ingredients: ['Pearl Powder', 'Shea Butter', 'Gold Leaf', 'Hyaluronic Acid'], howToUse: 'Apply to face and neck after toner. Pat gently to absorb. Use morning and evening.' },
  { id: 12, name: 'Rose Oil', price: 44.99, category: 'skincare', image: '/luxury-rose-oil-bottle.jpg', images: ['/luxury-rose-oil-bottle.jpg', '/luxury-rose-oil-bottle.jpg', '/luxury-rose-oil-bottle.jpg'], ingredients: ['Rose Hip Oil', 'Jojoba Oil', 'Argan Oil', 'Vitamin E'], howToUse: 'Use 2-3 drops on damp skin. Gently massage in circular motions. Can be used as night oil.' },
  { id: 13, name: 'Glow Toner', price: 34.99, category: 'skincare', image: '/luxury-purple-toner-bottle.jpg', images: ['/luxury-purple-toner-bottle.jpg', '/luxury-purple-toner-bottle.jpg', '/luxury-purple-toner-bottle.jpg'], ingredients: ['Niacinamide', 'Glycerin', 'Witch Hazel', 'Vitamin B3'], howToUse: 'Apply with cotton pad after cleansing. Swipe across face gently. Follow with moisturizer.' },
  { id: 14, name: 'Night Elixir', price: 54.99, category: 'skincare', image: '/luxury-night-serum-bottle.jpg', images: ['/luxury-night-serum-bottle.jpg', '/luxury-night-serum-bottle.jpg', '/luxury-night-serum-bottle.jpg'], ingredients: ['Retinol', 'Squalane', 'Peptides', 'Lavender Oil'], howToUse: 'Apply to clean skin before bed. Use 3-4 nights weekly. Follow with night cream.' },

  // Makeup
  { id: 15, name: 'Luxury Lipstick', price: 38, category: 'makeup', image: '/luxury-lipstick-makeup.jpg', images: ['/luxury-lipstick-makeup.jpg', '/luxury-lipstick-makeup.jpg', '/luxury-lipstick-makeup.jpg'], ingredients: ['Beeswax', 'Jojoba Oil', 'Vitamin E', 'Color Pigments'], howToUse: 'Apply directly to lips. Use lip liner for precision. Reapply as needed throughout the day.' },
  { id: 16, name: 'Foundation Primer', price: 35, category: 'makeup', image: '/foundation-primer-makeup.jpg', images: ['/foundation-primer-makeup.jpg', '/foundation-primer-makeup.jpg', '/foundation-primer-makeup.jpg'], ingredients: ['Silicones', 'Glycerin', 'Vitamin E', 'Mineral Pigments'], howToUse: 'Apply to clean, moisturized skin. Wait 1-2 minutes. Apply foundation over primer.' },
  { id: 17, name: 'Mascara Pro', price: 32, category: 'makeup', image: '/mascara-professional-makeup.jpg', images: ['/mascara-professional-makeup.jpg', '/mascara-professional-makeup.jpg', '/mascara-professional-makeup.jpg'], ingredients: ['Waxes', 'Film-forming Agents', 'Pigments', 'Oils'], howToUse: 'Wiggle brush from lash root to tip. Apply 2-3 coats for desired volume. Remove with makeup remover.' },
  { id: 18, name: 'Eye Shadow Palette', price: 55, category: 'makeup', image: '/eyeshadow-palette-makeup.jpg', images: ['/eyeshadow-palette-makeup.jpg', '/eyeshadow-palette-makeup.jpg', '/eyeshadow-palette-makeup.jpg'], ingredients: ['Mica', 'Talc', 'Iron Oxides', 'Titanium Dioxide'], howToUse: 'Apply with brush or finger to eyelids. Blend for seamless finish. Use eyeshadow primer for longevity.' },
  { id: 19, name: 'Blush', price: 28, category: 'makeup', image: '/blush-makeup-product.jpg', images: ['/blush-makeup-product.jpg', '/blush-makeup-product.jpg', '/blush-makeup-product.jpg'], ingredients: ['Talc', 'Mica', 'Color Pigments', 'Oils'], howToUse: 'Apply to apples of cheeks with fluffy brush. Blend upward toward temples for natural look.' },
  { id: 20, name: 'Eyeliner', price: 22, category: 'makeup', image: '/eyeliner-makeup.jpg', images: ['/eyeliner-makeup.jpg', '/eyeliner-makeup.jpg', '/eyeliner-makeup.jpg'], ingredients: ['Waxes', 'Film-formers', 'Pigments', 'Emollients'], howToUse: 'Apply along upper lash line. Create winged effect if desired. Use liquid for precision, pencil for softness.' },
  { id: 21, name: 'Foundation', price: 48, category: 'makeup', image: '/foundation-makeup-product.jpg', images: ['/foundation-makeup-product.jpg', '/foundation-makeup-product.jpg', '/foundation-makeup-product.jpg'], ingredients: ['Water', 'Silicones', 'Pigments', 'Preservatives'], howToUse: 'Apply with brush, sponge, or fingers. Blend outward from center of face for even coverage.' },
  { id: 22, name: 'Highlighter', price: 32, category: 'makeup', image: '/highlighter-makeup-product.jpg', images: ['/highlighter-makeup-product.jpg', '/highlighter-makeup-product.jpg', '/highlighter-makeup-product.jpg'], ingredients: ['Mica', 'Silica', 'Color Pigments', 'Binders'], howToUse: 'Apply to high points of face: cheekbones, brow bone, bridge of nose. Blend gently for glow.' },
  { id: 23, name: 'Liquid Lipstick', price: 29.99, category: 'makeup', image: '/liquid-lipstick-makeup.jpg', images: ['/liquid-lipstick-makeup.jpg', '/liquid-lipstick-makeup.jpg', '/liquid-lipstick-makeup.jpg'], ingredients: ['Film-formers', 'Resins', 'Pigments', 'Emollients'], howToUse: 'Apply with precision applicator. Start from center of lips and glide outward. Allow to set.' },

  // Fragrance
  { id: 24, name: 'Floral Fragrance', price: 85, category: 'fragrance', image: '/floral-fragrance-perfume.jpg', images: ['/floral-fragrance-perfume.jpg', '/floral-fragrance-perfume.jpg', '/floral-fragrance-perfume.jpg'], ingredients: ['Rose', 'Jasmine', 'Peony', 'Vanilla'], howToUse: 'Spray 2-3 times on pulse points: wrists, neck, behind ears. Dab to diffuse if desired.' },
  { id: 25, name: 'Vanilla Fragrance', price: 75, category: 'fragrance', image: '/vanilla-fragrance-perfume.jpg', images: ['/vanilla-fragrance-perfume.jpg', '/vanilla-fragrance-perfume.jpg', '/vanilla-fragrance-perfume.jpg'], ingredients: ['Vanilla', 'Caramel', 'Amber', 'Musk'], howToUse: 'Apply to pulse points for optimal diffusion. Reapply as needed throughout the day.' },
  { id: 26, name: 'Citrus Splash', price: 68, category: 'fragrance', image: '/citrus-splash-perfume.jpg', images: ['/citrus-splash-perfume.jpg', '/citrus-splash-perfume.jpg', '/citrus-splash-perfume.jpg'], ingredients: ['Lemon', 'Orange', 'Bergamot', 'Grapefruit'], howToUse: 'Spray on pulse points. Perfect for daytime. Freshens throughout the day with reapplication.' },
  { id: 27, name: 'Woody Essence', price: 92, category: 'fragrance', image: '/woody-essence-perfume.jpg', images: ['/woody-essence-perfume.jpg', '/woody-essence-perfume.jpg', '/woody-essence-perfume.jpg'], ingredients: ['Sandalwood', 'Cedarwood', 'Vetiver', 'Patchouli'], howToUse: 'Apply to warm areas of body: wrists, chest, inner elbows for best diffusion.' },
  { id: 28, name: 'Ocean Breeze', price: 72, category: 'fragrance', image: '/ocean-breeze-perfume.jpg', images: ['/ocean-breeze-perfume.jpg', '/ocean-breeze-perfume.jpg', '/ocean-breeze-perfume.jpg'], ingredients: ['Sea Salt', 'Aquatic Notes', 'Driftwood', 'Seaweed'], howToUse: 'Perfect for warm weather. Apply generously to pulse points and clothing.' },
  { id: 29, name: 'Rose Garden', price: 88, category: 'fragrance', image: '/rose-garden-perfume.jpg', images: ['/rose-garden-perfume.jpg', '/rose-garden-perfume.jpg', '/rose-garden-perfume.jpg'], ingredients: ['Rose', 'Gardenia', 'Lily', 'Green Notes'], howToUse: 'Spray on pulse points for lasting fragrance. Ideal for romantic occasions.' },
  { id: 30, name: 'Musk Elegance', price: 78, category: 'fragrance', image: '/musk-elegance-perfume.jpg', images: ['/musk-elegance-perfume.jpg', '/musk-elegance-perfume.jpg', '/musk-elegance-perfume.jpg'], ingredients: ['Musk', 'Amber', 'Vanilla', 'Sandalwood'], howToUse: 'Apply to skin for sensual, lasting fragrance. Creates a beautiful personal scent profile.' },
  { id: 31, name: 'Jasmine Night', price: 82, category: 'fragrance', image: '/jasmine-night-perfume.jpg', images: ['/jasmine-night-perfume.jpg', '/jasmine-night-perfume.jpg', '/jasmine-night-perfume.jpg'], ingredients: ['Jasmine', 'Tuberose', 'Ylang Ylang', 'Tonka'], howToUse: 'Perfect for evening wear. Apply to pulse points for optimal scent throw.' },
  { id: 32, name: 'Lavender Essence', price: 64.99, category: 'fragrance', image: '/lavender-essence-perfume.jpg', images: ['/lavender-essence-perfume.jpg', '/lavender-essence-perfume.jpg', '/lavender-essence-perfume.jpg'], ingredients: ['Lavender', 'Chamomile', 'Eucalyptus', 'Bergamot'], howToUse: 'Apply to pulse points. Calming scent perfect for relaxation and everyday wear.' },

  // Wellness
  { id: 33, name: 'Hair Growth Supplement', price: 48, category: 'wellness', image: '/hair-growth-supplement.jpg', images: ['/hair-growth-supplement.jpg', '/hair-growth-supplement.jpg', '/hair-growth-supplement.jpg'], ingredients: ['Biotin', 'Collagen', 'Keratin', 'Vitamins B & C'], howToUse: 'Take 2 capsules daily with water. Best results after 3 months of consistent use.' },
  { id: 34, name: 'Collagen Powder', price: 55, category: 'wellness', image: '/collagen-powder-beauty.jpg', images: ['/collagen-powder-beauty.jpg', '/collagen-powder-beauty.jpg', '/collagen-powder-beauty.jpg'], ingredients: ['Hydrolyzed Collagen', 'Vitamin C', 'Hyaluronic Acid', 'Biotin'], howToUse: 'Mix 1 scoop with water or beverage daily. Best taken in the morning.' },
  { id: 35, name: 'Vitamin Serum', price: 52, category: 'wellness', image: '/vitamin-serum-wellness.jpg', images: ['/vitamin-serum-wellness.jpg', '/vitamin-serum-wellness.jpg', '/vitamin-serum-wellness.jpg'], ingredients: ['Vitamin C', 'Vitamin E', 'Vitamin B Complex', 'Antioxidants'], howToUse: 'Apply 2-3 drops to face daily. Use morning and night for best results.' },
  { id: 36, name: 'Hydration Tablets', price: 35, category: 'wellness', image: '/hydration-tablets-wellness.jpg', images: ['/hydration-tablets-wellness.jpg', '/hydration-tablets-wellness.jpg', '/hydration-tablets-wellness.jpg'], ingredients: ['Electrolytes', 'Coconut Water', 'Vitamin B', 'Minerals'], howToUse: 'Dissolve 1 tablet in water. Drink throughout the day for optimal hydration.' },
  { id: 37, name: 'Skin Glow Capsules', price: 62, category: 'wellness', image: '/skin-glow-capsules.jpg', images: ['/skin-glow-capsules.jpg', '/skin-glow-capsules.jpg', '/skin-glow-capsules.jpg'], ingredients: ['Astaxanthin', 'Lutein', 'Selenium', 'Vitamin A'], howToUse: 'Take 1 capsule daily with meals. Consistent use recommended for visible glow.' },
  { id: 38, name: 'Bio Serum', price: 45, category: 'wellness', image: '/bio-serum-wellness.jpg', images: ['/bio-serum-wellness.jpg', '/bio-serum-wellness.jpg', '/bio-serum-wellness.jpg'], ingredients: ['Bioactive Peptides', 'Marine Extract', 'Hyaluronic Acid', 'CoQ10'], howToUse: 'Apply 3-5 drops to face and neck daily. Massage gently until absorbed.' },
  { id: 39, name: 'Antioxidant Blend', price: 58, category: 'wellness', image: '/antioxidant-blend-wellness.jpg', images: ['/antioxidant-blend-wellness.jpg', '/antioxidant-blend-wellness.jpg', '/antioxidant-blend-wellness.jpg'], ingredients: ['Green Tea Extract', 'Resveratrol', 'Quercetin', 'Polyphenols'], howToUse: 'Mix 1 scoop daily with water or juice. Antioxidant protection for overall wellness.' },
  { id: 40, name: 'Youth Complex', price: 70, category: 'wellness', image: '/youth-complex-supplement.jpg', images: ['/youth-complex-supplement.jpg', '/youth-complex-supplement.jpg', '/youth-complex-supplement.jpg'], ingredients: ['NAD+', 'Telomerase Activators', 'Mitochondrial Support', 'Anti-Aging Complex'], howToUse: 'Take 2 capsules daily. Best results when combined with healthy lifestyle.' },

  // Sets
  { id: 41, name: 'Skincare Starter Set', price: 89, category: 'sets', image: '/skincare-starter-set.jpg', images: ['/skincare-starter-set.jpg', '/skincare-starter-set.jpg', '/skincare-starter-set.jpg'], ingredients: ['Multiple skincare actives'], howToUse: 'Use each product as directed. Complete skincare routine included.' },
  { id: 42, name: 'Makeup Essentials Bundle', price: 125, category: 'sets', image: '/makeup-essentials-bundle.jpg', images: ['/makeup-essentials-bundle.jpg', '/makeup-essentials-bundle.jpg', '/makeup-essentials-bundle.jpg'], ingredients: ['Various makeup pigments and binders'], howToUse: 'All essential makeup products included. Apply as desired.' },
  { id: 43, name: 'Luxury Travel Set', price: 79, category: 'sets', image: '/luxury-travel-set.jpg', images: ['/luxury-travel-set.jpg', '/luxury-travel-set.jpg', '/luxury-travel-set.jpg'], ingredients: ['Travel-size luxury products'], howToUse: 'Portable sizes for on-the-go beauty routine. TSA compliant.' },
  { id: 44, name: 'Date Night Set', price: 95, category: 'sets', image: '/date-night-makeup-set.jpg', images: ['/date-night-makeup-set.jpg', '/date-night-makeup-set.jpg', '/date-night-makeup-set.jpg'], ingredients: ['Glamorous makeup and fragrance'], howToUse: 'Create stunning date night looks with this complete collection.' },
  { id: 45, name: 'Glow Getter Set', price: 110, category: 'sets', image: '/glow-getter-set.jpg', images: ['/glow-getter-set.jpg', '/glow-getter-set.jpg', '/glow-getter-set.jpg'], ingredients: ['Glowing skincare and makeup'], howToUse: 'Achieve radiant glowing skin with this complete routine.' },
  { id: 46, name: 'Wellness Bundle', price: 135, category: 'sets', image: '/wellness-bundle-set.jpg', images: ['/wellness-bundle-set.jpg', '/wellness-bundle-set.jpg', '/wellness-bundle-set.jpg'], ingredients: ['Complete wellness products'], howToUse: 'Full wellness routine for complete beauty and health.' },
  { id: 47, name: 'Complete Beauty Set', price: 150, category: 'sets', image: '/complete-beauty-set.jpg', images: ['/complete-beauty-set.jpg', '/complete-beauty-set.jpg', '/complete-beauty-set.jpg'], ingredients: ['Full beauty collection'], howToUse: 'Everything needed for complete beauty routine.' },
  { id: 48, name: 'Signature Collection', price: 180, category: 'sets', image: '/signature-collection-set.jpg', images: ['/signature-collection-set.jpg', '/signature-collection-set.jpg', '/signature-collection-set.jpg'], ingredients: ['Premium signature products'], howToUse: 'Luxury signature products for elevated beauty experience.' },

  // Haircare
  { id: 49, name: 'Volumizing Shampoo', price: 32, category: 'haircare', image: '/volumizing-shampoo-haircare.jpg', images: ['/volumizing-shampoo-haircare.jpg', '/volumizing-shampoo-haircare.jpg', '/volumizing-shampoo-haircare.jpg'], ingredients: ['Volumizing Polymers', 'Wheat Protein', 'Panthenol', 'Biotin'], howToUse: 'Wet hair with warm water. Apply shampoo, massage scalp. Rinse thoroughly.' },
  { id: 50, name: 'Deep Conditioner', price: 38, category: 'haircare', image: '/deep-conditioner-haircare.jpg', images: ['/deep-conditioner-haircare.jpg', '/deep-conditioner-haircare.jpg', '/deep-conditioner-haircare.jpg'], ingredients: ['Keratin', 'Argan Oil', 'Shea Butter', 'Silk Proteins'], howToUse: 'Apply to damp hair from mid-length to ends. Leave for 10-15 minutes. Rinse.' },
  { id: 51, name: 'Hair Growth Serum', price: 48, category: 'haircare', image: '/hair-growth-serum.jpg', images: ['/hair-growth-serum.jpg', '/hair-growth-serum.jpg', '/hair-growth-serum.jpg'], ingredients: ['Minoxidil', 'Caffeine', 'Biotin', 'Plant Extracts'], howToUse: 'Apply directly to scalp daily. Massage gently. Best results after 3-6 months.' },
  { id: 52, name: 'Silk Hair Mask', price: 42, category: 'haircare', image: '/silk-hair-mask-treatment.jpg', images: ['/silk-hair-mask-treatment.jpg', '/silk-hair-mask-treatment.jpg', '/silk-hair-mask-treatment.jpg'], ingredients: ['Silk Proteins', 'Hyaluronic Acid', 'Panthenol', 'Vitamin E'], howToUse: 'Apply to hair after shampooing. Leave for 20 minutes. Rinse thoroughly.' },
  { id: 53, name: 'Keratin Treatment', price: 55, category: 'haircare', image: '/keratin-treatment-haircare.jpg', images: ['/keratin-treatment-haircare.jpg', '/keratin-treatment-haircare.jpg', '/keratin-treatment-haircare.jpg'], ingredients: ['Brazilian Keratin', 'Collagen', 'Amino Acids', 'Formaldehyde-free'], howToUse: 'Apply to damp hair. Leave for 60 minutes. Dry and straighten hair. Results last 3-4 weeks.' },
  { id: 54, name: 'Anti-Frizz Spray', price: 28, category: 'haircare', image: '/anti-frizz-spray-haircare.jpg', images: ['/anti-frizz-spray-haircare.jpg', '/anti-frizz-spray-haircare.jpg', '/anti-frizz-spray-haircare.jpg'], ingredients: ['Silicone Oil', 'Argan Oil', 'Vitamin E', 'UV Protectant'], howToUse: 'Spray on dry or damp hair before styling. Distributes evenly for frizz control.' },
  { id: 55, name: 'Hair Oil Elixir', price: 35, category: 'haircare', image: '/hair-oil-elixir.jpg', images: ['/hair-oil-elixir.jpg', '/hair-oil-elixir.jpg', '/hair-oil-elixir.jpg'], ingredients: ['Argan Oil', 'Coconut Oil', 'Jojoba Oil', 'Lavender Essential Oil'], howToUse: 'Apply to hair tips and ends. Use as overnight treatment or styling oil.' },
  { id: 56, name: 'Scalp Therapy Shampoo', price: 36, category: 'haircare', image: '/scalp-therapy-shampoo.jpg', images: ['/scalp-therapy-shampoo.jpg', '/scalp-therapy-shampoo.jpg', '/scalp-therapy-shampoo.jpg'], ingredients: ['Salicylic Acid', 'Tea Tree Oil', 'Zinc Pyrithione', 'Aloe Vera'], howToUse: 'Apply to scalp, massage for 2-3 minutes. Rinse thoroughly. Use 2-3 times weekly.' },
]

const FA_PRODUCT_NAMES: Record<number,string> = {
  1:'سرم آبرسان صورت',2:'کرم دور چشم',3:'مرطوب‌کننده SPF',4:'پاک‌کننده صورت',5:'کرم شب',6:'ماسک صورت',7:'تونر صورت',8:'درمان رتینول',
  9:'سرم ابریشمی',10:'ماسک اسطوخودوس',11:'کرم مروارید',12:'روغن رز',13:'تونر درخشان‌کننده',14:'اکسیر شب',
  15:'رژ لب لوکس',16:'پرایمر کرم‌پودر',17:'ریمل حرفه‌ای',18:'پالت سایه چشم',19:'رژگونه',20:'خط چشم',21:'کرم‌پودر',22:'هایلایتر',23:'رژ لب مایع',
  24:'عطر گلی',25:'عطر وانیلی',26:'اسپلش مرکبات',27:'اسانس چوبی',28:'نسیم اقیانوس',29:'باغ رز',30:'مشک الگانس',31:'یاس شب',32:'اسانس اسطوخودوس',
  33:'مکمل رشد مو',34:'پودر کلاژن',35:'سرم ویتامینه',36:'قرص آبرسان',37:'کپسول درخشش پوست',38:'سرم بایو',39:'ترکیب آنتی‌اکسیدان',40:'کمپلکس جوانی',
  41:'ست شروع مراقبت پوست',42:'باندل ضروری آرایش',43:'ست سفر لوکس',44:'ست دیت نایت',45:'ست درخشش',46:'باندل سلامت و زیبایی',47:'ست کامل زیبایی',48:'کالکشن امضا',
  49:'شامپو حجم‌دهنده',50:'نرم‌کننده عمیق',51:'سرم رشد مو',52:'ماسک ابریشمی مو',53:'درمان کراتین',54:'اسپری ضد وز',55:'اکسیر روغن مو',56:'شامپو درمان پوست سر'
}

export const ALL_PRODUCTS = PRODUCTS_SOURCE.map(product => ({
  ...product,
  englishName: product.name,
  name: FA_PRODUCT_NAMES[product.id] || product.name,
  ingredients: translateIngredientsFa(product.ingredients || []),
  howToUse: FA_HOW_TO_USE[product.id] || product.howToUse,
}))

export const searchProducts = (query: string) => {
  if (!query.trim()) return []
  const aliases: Record<string,string> = {
    'پوست':'skincare','مراقبت پوست':'skincare','سرم':'serum','کرم':'cream','ماسک':'mask',
    'آرایش':'makeup','رژ':'lipstick','ریمل':'mascara','خط چشم':'eyeliner','کرم پودر':'foundation',
    'عطر':'fragrance','ادکلن':'fragrance','مو':'haircare','مراقبت مو':'haircare','شامپو':'shampoo',
    'ست':'sets','هدیه':'sets','سلامت':'wellness'
  }
  const raw=query.trim().toLowerCase()
  const normalized=aliases[raw] || raw
  return ALL_PRODUCTS.filter(product =>
    product.name.toLowerCase().includes(normalized) ||
    product.englishName.toLowerCase().includes(normalized) ||
    product.category.toLowerCase().includes(normalized)
  ).slice(0, 8)
}

export const categoryLabelFa = (category: string) => ({skincare:'مراقبت پوست',makeup:'آرایش',fragrance:'عطر',wellness:'سلامت و زیبایی',sets:'ست‌ها',haircare:'مراقبت مو'} as Record<string,string>)[category] || category

export const getProductById = (id: number) => {
  return ALL_PRODUCTS.find(product => product.id === id)
}
